package contract

import (
	"archive/tar"
	"bytes"
	"os"
	"path/filepath"
	"testing"
)

func TestExtractArchiveIgnoresPAXGlobalMetadata(t *testing.T) {
	var archive bytes.Buffer
	writer := tar.NewWriter(&archive)
	if err := writer.WriteHeader(&tar.Header{
		Name:     "pax_global_header",
		Typeflag: tar.TypeXGlobalHeader,
		PAXRecords: map[string]string{
			"comment": "generated by Git on macOS",
		},
	}); err != nil {
		t.Fatal(err)
	}
	content := []byte("verified snapshot\n")
	if err := writer.WriteHeader(&tar.Header{
		Name:     "nested/file.txt",
		Mode:     0o644,
		Size:     int64(len(content)),
		Typeflag: tar.TypeReg,
	}); err != nil {
		t.Fatal(err)
	}
	if _, err := writer.Write(content); err != nil {
		t.Fatal(err)
	}
	if err := writer.Close(); err != nil {
		t.Fatal(err)
	}

	root := t.TempDir()
	if err := extractArchive(root, bytes.NewReader(archive.Bytes())); err != nil {
		t.Fatal(err)
	}
	got, err := os.ReadFile(filepath.Join(root, "nested", "file.txt"))
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(got, content) {
		t.Fatalf("content=%q", got)
	}
	if _, err := os.Stat(filepath.Join(root, "pax_global_header")); !os.IsNotExist(err) {
		t.Fatalf("global PAX metadata materialized as a file: %v", err)
	}
}
